title: User Guide
description: Documentation for xxx
theme: just-the-docs

url: ""

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template

color_scheme: dark

# For copy button on code
enable_copy_code_button: true
